name: Deploy NestJS Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nest-backend .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nest-backend

      - name: Deploy EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            docker pull ${{ secrets.DOCKER_USERNAME }}/nest-backend

            docker stop mongo_db || true
            docker rm mongo_db || true

            docker stop nest-backend || true
            docker rm nest-backend || true

            # MongoDB container
            docker run -d \
            --name mongo_db \
            -p 27017:27017 \
            -v mongo_data:/data/db \
            mongo:6

            # Backend container
            docker run -d \
            -p 8000:8000 \
            --name nest-backend \
            --link mongo_db \
            -e MONGO_URI=mongodb://mongo_db:27017/backend \
            ${{ secrets.DOCKER_USERNAME }}/nest-backend